// GENERATED by scripts/gen-methods.ts — do not edit by hand.
import type { Method } from './methods.types'

export const methods: Method[] = [
  {
    "name": "kb.capabilities",
    "group": "read",
    "mutates": false,
    "gated": false,
    "summary": "Return the protocol capabilities of this server: version, supported methods, retrieval backends, transports, review-gated flag, scoping config, and context engines.",
    "params": [],
    "returns": "Capabilities object: {name, version, spec, level, methods[], retrieval[] (e.g. fts5/substring/embedding/hybrid), review_gated, transports[], knowledge_capability{}, scoping{}, context_engines[]}.",
    "view": "dashboard",
    "longRunning": false
  },
  {
    "name": "kb.status",
    "group": "read",
    "mutates": false,
    "gated": false,
    "summary": "Return KB artifact counts and a health summary.",
    "params": [],
    "returns": "Status dict with per-kind artifact counts (claims, pages, entities, relations, sources, proposals) and a health summary.",
    "view": "dashboard",
    "longRunning": false
  },
  {
    "name": "kb.stats",
    "group": "audit",
    "mutates": false,
    "gated": false,
    "summary": "Observability snapshot: pending proposals by agent, review/approval rates, and citation coverage over a decision window.",
    "params": [
      {
        "name": "days",
        "type": "integer",
        "required": false,
        "default": "30",
        "description": "Decision window in days; 0 means all-time. JSONL coerces to int.",
        "control": "integer"
      }
    ],
    "returns": "Stats dict covering pending-by-agent counts, review/approval rates, and citation coverage for the window.",
    "view": "dashboard",
    "longRunning": false
  },
  {
    "name": "kb.search",
    "group": "search",
    "mutates": false,
    "gated": false,
    "summary": "Search the KB across retrieval backends with optional viewer-scope filtering.",
    "params": [
      {
        "name": "query",
        "type": "string",
        "required": true,
        "default": "",
        "description": "The search query string. Required (KeyError if omitted over JSONL).",
        "control": "textarea"
      },
      {
        "name": "limit",
        "type": "integer",
        "required": false,
        "default": "10",
        "description": "Maximum number of hits to return after scope filtering.",
        "control": "integer"
      },
      {
        "name": "backend",
        "type": "string",
        "required": false,
        "default": "auto",
        "description": "One of: auto (embedding then fts5 then substring), embedding, fts5, substring, hybrid. Unknown values raise an error.",
        "control": "select",
        "enum": [
          "auto",
          "embedding",
          "fts5",
          "substring",
          "hybrid"
        ]
      },
      {
        "name": "min_score",
        "type": "number",
        "required": false,
        "default": "0.0",
        "description": "Minimum relevance score for embedding/hybrid backends; lower-scoring hits are dropped.",
        "control": "slider"
      },
      {
        "name": "project",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Optional viewer project context used for scope filtering (null/unset = no project narrowing).",
        "control": "text"
      },
      {
        "name": "agent",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Optional viewer agent context used for scope filtering (null/unset = no agent narrowing).",
        "control": "text"
      }
    ],
    "returns": "Dict {backend (the backend actually used), viewer:{project,agent}, hits:[{kind, id, snippet, score, backend}]}.",
    "view": "search",
    "longRunning": false
  },
  {
    "name": "kb.neighbors",
    "group": "graph",
    "mutates": false,
    "gated": false,
    "summary": "Return graph neighbors of a claim, page, entity, or source node up to a given depth.",
    "params": [
      {
        "name": "node_id",
        "type": "string",
        "required": true,
        "default": "",
        "description": "Id of the node (claim/page/entity/source) to expand from. Required.",
        "control": "text",
        "refKind": "node"
      },
      {
        "name": "depth",
        "type": "integer",
        "required": false,
        "default": "1",
        "description": "Number of edge hops to traverse outward from node_id.",
        "control": "integer"
      },
      {
        "name": "rel_types",
        "type": "array<string>",
        "required": false,
        "default": "",
        "description": "Optional allow-list of relation types to follow (e.g. uses, depends_on); null = all types.",
        "control": "tags"
      },
      {
        "name": "max_nodes",
        "type": "integer",
        "required": false,
        "default": "50",
        "description": "Cap on the number of nodes returned in the neighborhood.",
        "control": "integer"
      }
    ],
    "returns": "Graph neighborhood dict (nodes and edges within depth of node_id). Raises if node_id is unknown.",
    "view": "graph",
    "longRunning": false
  },
  {
    "name": "kb.context",
    "group": "read",
    "mutates": false,
    "gated": false,
    "summary": "Build a ContextPack of ranked retrieved items ready to inject into an agent prompt, with optional quality gates and graph expansion.",
    "params": [
      {
        "name": "task",
        "type": "string",
        "required": true,
        "default": "",
        "description": "The task/query string used to retrieve and rank context items. Required.",
        "control": "textarea"
      },
      {
        "name": "limit",
        "type": "integer",
        "required": false,
        "default": "10",
        "description": "Maximum number of context items to include.",
        "control": "integer"
      },
      {
        "name": "max_chars",
        "type": "integer",
        "required": false,
        "default": "",
        "description": "Optional character budget for the pack; null = no budget cap. Items may be omitted/clipped to fit.",
        "control": "integer"
      },
      {
        "name": "min_items",
        "type": "integer",
        "required": false,
        "default": "0",
        "description": "Minimum number of items required for the pack quality gate to pass.",
        "control": "integer"
      },
      {
        "name": "require_citations",
        "type": "boolean",
        "required": false,
        "default": "false",
        "description": "If true, items lacking citations are flagged and can fail the quality gate.",
        "control": "toggle"
      },
      {
        "name": "session_id",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Optional active session id; when set, the query is recorded for the entity-salience reflex and a _meta.vouch_salience sidebar may be attached.",
        "control": "text",
        "refKind": "session"
      },
      {
        "name": "project",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Optional viewer project context for scope filtering.",
        "control": "text"
      },
      {
        "name": "agent",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Optional viewer agent context for scope filtering.",
        "control": "text"
      },
      {
        "name": "expand_graph",
        "type": "boolean",
        "required": false,
        "default": "false",
        "description": "If true, expand the pack with graph-neighbor items of the top hits.",
        "control": "toggle"
      },
      {
        "name": "graph_depth",
        "type": "integer",
        "required": false,
        "default": "1",
        "description": "Hop depth for graph expansion when expand_graph is true.",
        "control": "integer"
      },
      {
        "name": "graph_limit",
        "type": "integer",
        "required": false,
        "default": "20",
        "description": "Maximum number of additional items pulled in via graph expansion.",
        "control": "integer"
      },
      {
        "name": "fail_on_warnings",
        "type": "boolean",
        "required": false,
        "default": "false",
        "description": "JSONL-only param: if true, the quality gate fails when any warnings are present. Not exposed on the MCP tool signature.",
        "control": "toggle"
      },
      {
        "name": "fail_on_budget_truncation",
        "type": "boolean",
        "required": false,
        "default": "false",
        "description": "JSONL-only param: if true, the quality gate fails when the char budget truncated items. Not exposed on the MCP tool signature.",
        "control": "toggle"
      },
      {
        "name": "graph_rel_types",
        "type": "array<string>",
        "required": false,
        "default": "",
        "description": "JSONL-only param: optional relation-type allow-list for graph expansion; null = all types. Not exposed on the MCP tool signature.",
        "control": "tags"
      }
    ],
    "returns": "ContextPack dict {query, generated_at, items:[{id, type, summary, score, backend, citations[], freshness}], quality:{ok, minimum_items, require_citations, ...}, warnings[]}, optionally with a _meta.vouch_salience sidebar when session_id is set.",
    "view": "search",
    "longRunning": false
  },
  {
    "name": "kb.synthesize",
    "group": "read",
    "mutates": false,
    "gated": false,
    "summary": "Answer a query from approved claims only, returning prose with inline [claim_id] citations, an explicit gaps block, and a synthesis_confidence grade. Unlike kb.context (a ranked list), every sentence is traceable to an approved claim.",
    "params": [
      {
        "name": "query",
        "type": "string",
        "required": true,
        "default": "",
        "description": "The question to answer from approved claims. Required.",
        "control": "textarea"
      },
      {
        "name": "depth",
        "type": "integer",
        "required": false,
        "default": "3",
        "description": "How many hops/levels of claims to draw on when composing the answer.",
        "control": "integer"
      },
      {
        "name": "max_chars",
        "type": "integer",
        "required": false,
        "default": "4000",
        "description": "Character budget for the synthesized answer prose.",
        "control": "integer"
      },
      {
        "name": "llm",
        "type": "boolean",
        "required": false,
        "default": "false",
        "description": "JSONL-only param: if true, use an LLM to compose the synthesis rather than the deterministic composer. Not exposed on the MCP tool signature.",
        "control": "toggle"
      }
    ],
    "returns": "Synthesis dict: prose answer with inline [claim_id] citations, a gaps block listing what could not be answered, and a synthesis_confidence grade.",
    "view": "search",
    "longRunning": true
  },
  {
    "name": "kb.read_page",
    "group": "read",
    "mutates": false,
    "gated": false,
    "summary": "Return a single page by id (title, body, type, status, and linked claim/entity/source ids).",
    "params": [
      {
        "name": "page_id",
        "type": "string",
        "required": true,
        "default": "",
        "description": "Id of the page to fetch. Required; raises if not found.",
        "control": "text",
        "refKind": "page"
      }
    ],
    "returns": "Page object {id, title, body, type, status, claims[], entities[], sources[], tags[], metadata{}, created_at, updated_at}.",
    "view": "browse",
    "longRunning": false
  },
  {
    "name": "kb.read_claim",
    "group": "read",
    "mutates": false,
    "gated": false,
    "summary": "Return a single claim by id, including its citation/evidence list and lifecycle metadata.",
    "params": [
      {
        "name": "claim_id",
        "type": "string",
        "required": true,
        "default": "",
        "description": "Id of the claim to fetch. Required; raises if not found.",
        "control": "text",
        "refKind": "claim"
      }
    ],
    "returns": "Claim object {id, text, type, status, confidence, evidence[], entities[], supersedes[], superseded_by, contradicts[], scope, tags[], created_at, updated_at, last_confirmed_at, approved_by}.",
    "view": "browse",
    "longRunning": false
  },
  {
    "name": "kb.read_entity",
    "group": "read",
    "mutates": false,
    "gated": false,
    "summary": "Return a single entity by id.",
    "params": [
      {
        "name": "entity_id",
        "type": "string",
        "required": true,
        "default": "",
        "description": "Id of the entity to fetch. Required; raises if not found.",
        "control": "text",
        "refKind": "entity"
      }
    ],
    "returns": "Entity object {id, name, type, aliases[], description, page, created_at, updated_at}.",
    "view": "browse",
    "longRunning": false
  },
  {
    "name": "kb.read_relation",
    "group": "read",
    "mutates": false,
    "gated": false,
    "summary": "Return a single relation (typed edge) by id.",
    "params": [
      {
        "name": "relation_id",
        "type": "string",
        "required": true,
        "default": "",
        "description": "Id of the relation to fetch. Required; raises if not found.",
        "control": "text",
        "refKind": "relation"
      }
    ],
    "returns": "Relation object {id, source, relation, target, confidence, evidence[], created_at, updated_at}.",
    "view": "browse",
    "longRunning": false
  },
  {
    "name": "kb.list_pages",
    "group": "list",
    "mutates": false,
    "gated": false,
    "summary": "List all pages in the KB. (MCP returns a compact id/title/type/tags view; JSONL returns full page objects.)",
    "params": [],
    "returns": "Array of pages. MCP: [{id, title, type, tags}]. JSONL: full Page objects {id, title, body, type, status, claims[], entities[], sources[], tags[], metadata{}, created_at, updated_at}.",
    "view": "browse",
    "longRunning": false
  },
  {
    "name": "kb.list_claims",
    "group": "list",
    "mutates": false,
    "gated": false,
    "summary": "List all claims, optionally filtered by status.",
    "params": [
      {
        "name": "status",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Optional ClaimStatus filter: working, actionable, stable, contested, superseded, archived, or redacted. Omit/null to list all.",
        "control": "select",
        "enum": [
          "working",
          "actionable",
          "stable",
          "contested",
          "superseded",
          "archived",
          "redacted"
        ]
      }
    ],
    "returns": "Array of full Claim objects {id, text, type, status, confidence, evidence[], entities[], supersedes[], superseded_by, contradicts[], scope, tags[], created_at, updated_at, last_confirmed_at, approved_by}.",
    "view": "browse",
    "longRunning": false
  },
  {
    "name": "kb.list_entities",
    "group": "list",
    "mutates": false,
    "gated": false,
    "summary": "List all entities, optionally filtered by entity type.",
    "params": [
      {
        "name": "entity_type",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Optional EntityType filter: person, project, repo, company, concept, decision, workflow, file, api, incident, source, agent, tool, team, or system. Omit/null to list all.",
        "control": "select",
        "enum": [
          "person",
          "project",
          "repo",
          "company",
          "concept",
          "decision",
          "workflow",
          "file",
          "api",
          "incident",
          "source",
          "agent",
          "tool",
          "team",
          "system"
        ]
      }
    ],
    "returns": "Array of full Entity objects {id, name, type, aliases[], description, page, created_at, updated_at}.",
    "view": "browse",
    "longRunning": false
  },
  {
    "name": "kb.list_relations",
    "group": "list",
    "mutates": false,
    "gated": false,
    "summary": "List all relations (typed edges between entities/claims/pages); if node_id is given, only edges touching that node.",
    "params": [
      {
        "name": "node_id",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Optional artifact id (entity/claim/page/source). When set, returns only relations whose source or target equals this id. Omit to list every relation.",
        "control": "text",
        "refKind": "node"
      }
    ],
    "returns": "Array of relation objects (Relation.model_dump): each has id, source, relation (one of: uses, depends_on, contradicts, supersedes, supports, caused_by, owned_by, derived_from, similar_to, blocks, implements, references, mentions, relates_to), target, confidence (0.0-1.0), evidence (list of ids), created_at, updated_at.",
    "view": "browse",
    "longRunning": false
  },
  {
    "name": "kb.list_sources",
    "group": "list",
    "mutates": false,
    "gated": false,
    "summary": "List all registered sources (immutable evidence inputs).",
    "params": [],
    "returns": "Array of source objects. Over MCP each item is trimmed to {id, title, type, locator, byte_size}; over JSONL it is the full Source.model_dump (adds hash, immutable, scope, media_type, created_at, metadata, tags). type is one of: file, url, transcript, message, commit, issue, screenshot, pdf, audio, video, folder.",
    "view": "browse",
    "longRunning": false
  },
  {
    "name": "kb.list_pending",
    "group": "list",
    "mutates": false,
    "gated": false,
    "summary": "List all proposals awaiting human review (the review-gate queue).",
    "params": [],
    "returns": "Array of Proposal objects (Proposal.model_dump): each has id, kind (claim|page|entity|relation), proposed_by, session_id, proposed_at, payload (the proposed artifact body), rationale, status (pending here), decided_at, decided_by, decision_reason.",
    "view": "review",
    "longRunning": false
  },
  {
    "name": "kb.register_source",
    "group": "propose",
    "mutates": true,
    "gated": false,
    "summary": "Register a source from inline content. Evidence intake is NOT gated; raw evidence is harmless and de-duplicated by content hash. Writes a source.add audit event.",
    "params": [
      {
        "name": "content",
        "type": "string",
        "required": true,
        "default": "",
        "description": "Raw source text. Encoded as UTF-8 and content-hashed to produce the source id (sha256).",
        "control": "textarea"
      },
      {
        "name": "title",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Optional human-facing title for the source.",
        "control": "text"
      },
      {
        "name": "url",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Optional URL. Also used as the locator when present.",
        "control": "text"
      },
      {
        "name": "source_type",
        "type": "string",
        "required": false,
        "default": "file",
        "description": "Source kind. One of: file, url, transcript, message, commit, issue, screenshot, pdf, audio, video, folder. Defaults to file.",
        "control": "select",
        "enum": [
          "file",
          "url",
          "transcript",
          "message",
          "commit",
          "issue",
          "screenshot",
          "pdf",
          "audio",
          "video",
          "folder"
        ]
      },
      {
        "name": "media_type",
        "type": "string",
        "required": false,
        "default": "text/plain",
        "description": "MIME type of the content. Defaults to text/plain.",
        "control": "text"
      }
    ],
    "returns": "The created Source object (Source.model_dump): id (sha256 hex), type, locator, title, hash, immutable, scope, byte_size, media_type, created_at, metadata, tags. Returns the existing source if the content hash already exists (dedupe).",
    "view": "propose",
    "longRunning": false
  },
  {
    "name": "kb.register_source_from_path",
    "group": "propose",
    "mutates": true,
    "gated": false,
    "summary": "Register a source by reading a file from disk (must be under the KB root). Not gated; writes a source.add audit event.",
    "params": [
      {
        "name": "path",
        "type": "string",
        "required": true,
        "default": "",
        "description": "Path to the file to ingest. Must resolve under the KB root (read_under_root enforces this). Its bytes are hashed to the source id.",
        "control": "file",
        "file": "under-root"
      },
      {
        "name": "title",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Optional title. Defaults to the file's basename when omitted.",
        "control": "text"
      },
      {
        "name": "url",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Optional URL associated with the source.",
        "control": "text"
      },
      {
        "name": "source_type",
        "type": "string",
        "required": false,
        "default": "file",
        "description": "Source kind. One of: file, url, transcript, message, commit, issue, screenshot, pdf, audio, video, folder. Defaults to file. (media_type is not accepted on this method; the locator is set to the on-disk path.)",
        "control": "select",
        "enum": [
          "file",
          "url",
          "transcript",
          "message",
          "commit",
          "issue",
          "screenshot",
          "pdf",
          "audio",
          "video",
          "folder"
        ]
      }
    ],
    "returns": "The created Source object (Source.model_dump): id (sha256 hex), type, locator (the on-disk path), title, hash, immutable, scope, byte_size, media_type, created_at, metadata, tags.",
    "view": "propose",
    "longRunning": false
  },
  {
    "name": "kb.propose_claim",
    "group": "propose",
    "mutates": true,
    "gated": true,
    "summary": "Propose a new claim (atomic durable assertion). Files a pending proposal; becomes a durable claim only after kb.approve.",
    "params": [
      {
        "name": "text",
        "type": "string",
        "required": true,
        "default": "",
        "description": "The claim assertion text â the smallest thing that can be cited, contradicted, or superseded.",
        "control": "textarea"
      },
      {
        "name": "evidence",
        "type": "array<string>",
        "required": true,
        "default": "",
        "description": "List of citation ids backing the claim â Source ids and/or Evidence ids. At least one is required (claims must cite their support).",
        "control": "tags",
        "refKind": "source",
        "refMulti": true
      },
      {
        "name": "claim_type",
        "type": "string",
        "required": false,
        "default": "observation",
        "description": "Claim type. One of: fact, decision, preference, workflow, observation, question, warning. Defaults to observation.",
        "control": "select",
        "enum": [
          "fact",
          "decision",
          "preference",
          "workflow",
          "observation",
          "question",
          "warning"
        ]
      },
      {
        "name": "confidence",
        "type": "number",
        "required": false,
        "default": "0.7",
        "description": "Confidence in the claim, 0.0-1.0. Defaults to 0.7.",
        "control": "slider"
      },
      {
        "name": "entities",
        "type": "array<string>",
        "required": false,
        "default": "",
        "description": "Optional list of entity ids this claim mentions/relates to.",
        "control": "tags",
        "refKind": "entity",
        "refMulti": true
      },
      {
        "name": "rationale",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Optional free-text rationale shown to the human reviewer at the gate.",
        "control": "textarea"
      },
      {
        "name": "tags",
        "type": "array<string>",
        "required": false,
        "default": "",
        "description": "Optional list of tags to attach to the claim.",
        "control": "tags"
      },
      {
        "name": "slug_hint",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Optional hint to influence the generated claim slug/id.",
        "control": "text"
      },
      {
        "name": "session_id",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Optional session id to associate the proposal with (so crystallize can later promote it).",
        "control": "text",
        "refKind": "session"
      },
      {
        "name": "dry_run",
        "type": "boolean",
        "required": false,
        "default": "false",
        "description": "When true, validate and preview without writing the proposal. Defaults to false.",
        "control": "toggle"
      }
    ],
    "returns": "A proposal-response object: {proposal_id, status (pending), kind (claim), dry_run, note} plus an optional warnings array. On dry_run the note reads 'dry run â not written'; otherwise 'pending human approval via vouch approve <id>'.",
    "view": "propose",
    "longRunning": false
  },
  {
    "name": "kb.propose_page",
    "group": "propose",
    "mutates": true,
    "gated": true,
    "summary": "Propose a new page (compiled, maintained markdown â entity write-up, decision record, session summary, etc.). Files a pending proposal; durable only after kb.approve.",
    "params": [
      {
        "name": "title",
        "type": "string",
        "required": true,
        "default": "",
        "description": "Page title.",
        "control": "text"
      },
      {
        "name": "body",
        "type": "string",
        "required": true,
        "default": "",
        "description": "Page body as plain markdown. Required over MCP; over JSONL it defaults to an empty string.",
        "control": "textarea"
      },
      {
        "name": "page_type",
        "type": "string",
        "required": false,
        "default": "concept",
        "description": "Page kind. Built-in values: entity, concept, decision, workflow, session, index, log, report, source-summary. A KB may also declare extra kinds in config.yaml (validated at the gate). Defaults to concept.",
        "control": "combobox",
        "enum": [
          "entity",
          "concept",
          "decision",
          "workflow",
          "session",
          "index",
          "log",
          "report",
          "source-summary"
        ],
        "combobox": true
      },
      {
        "name": "claim_ids",
        "type": "array<string>",
        "required": false,
        "default": "",
        "description": "Optional list of claim ids the page compiles/references.",
        "control": "tags",
        "refKind": "claim",
        "refMulti": true
      },
      {
        "name": "entity_ids",
        "type": "array<string>",
        "required": false,
        "default": "",
        "description": "Optional list of entity ids the page is about/references.",
        "control": "tags",
        "refKind": "entity",
        "refMulti": true
      },
      {
        "name": "source_ids",
        "type": "array<string>",
        "required": false,
        "default": "",
        "description": "Optional list of source ids the page draws from.",
        "control": "tags",
        "refKind": "source",
        "refMulti": true
      },
      {
        "name": "metadata",
        "type": "object",
        "required": false,
        "default": "",
        "description": "Optional per-kind frontmatter (e.g. a meeting-notes kind's attendees). Serialized into the on-disk YAML frontmatter.",
        "control": "json"
      },
      {
        "name": "rationale",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Optional rationale shown to the human reviewer at the gate.",
        "control": "textarea"
      },
      {
        "name": "slug_hint",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Optional hint to influence the generated page slug/id.",
        "control": "text"
      },
      {
        "name": "session_id",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Optional session id to associate the proposal with.",
        "control": "text",
        "refKind": "session"
      },
      {
        "name": "dry_run",
        "type": "boolean",
        "required": false,
        "default": "false",
        "description": "When true, validate and preview without writing the proposal. Defaults to false.",
        "control": "toggle"
      }
    ],
    "returns": "A proposal-response object: {proposal_id, status (pending), kind (page), dry_run, note} (MCP also includes an optional warnings array). Becomes a durable page after kb.approve.",
    "view": "propose",
    "longRunning": false
  },
  {
    "name": "kb.propose_entity",
    "group": "propose",
    "mutates": true,
    "gated": true,
    "summary": "Propose a new entity (a typed named thing â person, project, repo, concept, etc.). Files a pending proposal; durable only after kb.approve.",
    "params": [
      {
        "name": "name",
        "type": "string",
        "required": true,
        "default": "",
        "description": "Display name of the entity.",
        "control": "text"
      },
      {
        "name": "entity_type",
        "type": "string",
        "required": true,
        "default": "",
        "description": "Entity type. One of: person, project, repo, company, concept, decision, workflow, file, api, incident, source, agent, tool, team, system.",
        "control": "select",
        "enum": [
          "person",
          "project",
          "repo",
          "company",
          "concept",
          "decision",
          "workflow",
          "file",
          "api",
          "incident",
          "source",
          "agent",
          "tool",
          "team",
          "system"
        ]
      },
      {
        "name": "aliases",
        "type": "array<string>",
        "required": false,
        "default": "",
        "description": "Optional alternate names this entity is known by.",
        "control": "tags"
      },
      {
        "name": "description",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Optional short description of the entity.",
        "control": "textarea"
      },
      {
        "name": "rationale",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Optional rationale shown to the human reviewer at the gate.",
        "control": "textarea"
      },
      {
        "name": "slug_hint",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Optional hint to influence the generated entity slug/id.",
        "control": "text"
      },
      {
        "name": "session_id",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Optional session id to associate the proposal with.",
        "control": "text",
        "refKind": "session"
      },
      {
        "name": "dry_run",
        "type": "boolean",
        "required": false,
        "default": "false",
        "description": "When true, validate and preview without writing the proposal. Defaults to false.",
        "control": "toggle"
      }
    ],
    "returns": "A proposal-response object: {proposal_id, status (pending), kind (entity), dry_run, note} (MCP also includes an optional warnings array). Becomes a durable entity after kb.approve.",
    "view": "propose",
    "longRunning": false
  },
  {
    "name": "kb.propose_relation",
    "group": "propose",
    "mutates": true,
    "gated": true,
    "summary": "Propose a new relation (a typed edge between entities/claims/pages). Files a pending proposal; durable only after kb.approve.",
    "params": [
      {
        "name": "src",
        "type": "string",
        "required": true,
        "default": "",
        "description": "Id of the source/origin endpoint of the edge.",
        "control": "text",
        "refKind": "node"
      },
      {
        "name": "relation",
        "type": "string",
        "required": true,
        "default": "",
        "description": "Relation type. One of: uses, depends_on, contradicts, supersedes, supports, caused_by, owned_by, derived_from, similar_to, blocks, implements, references, mentions, relates_to.",
        "control": "select",
        "enum": [
          "uses",
          "depends_on",
          "contradicts",
          "supersedes",
          "supports",
          "caused_by",
          "owned_by",
          "derived_from",
          "similar_to",
          "blocks",
          "implements",
          "references",
          "mentions",
          "relates_to"
        ]
      },
      {
        "name": "target",
        "type": "string",
        "required": true,
        "default": "",
        "description": "Id of the target endpoint of the edge.",
        "control": "text",
        "refKind": "node"
      },
      {
        "name": "confidence",
        "type": "number",
        "required": false,
        "default": "0.7",
        "description": "Confidence in the relation, 0.0-1.0. Defaults to 0.7.",
        "control": "slider"
      },
      {
        "name": "evidence",
        "type": "array<string>",
        "required": false,
        "default": "",
        "description": "Optional list of citation ids (Source/Evidence) backing the relation.",
        "control": "tags",
        "refKind": "source",
        "refMulti": true
      },
      {
        "name": "rationale",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Optional rationale shown to the human reviewer at the gate.",
        "control": "textarea"
      },
      {
        "name": "session_id",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Optional session id to associate the proposal with.",
        "control": "text",
        "refKind": "session"
      },
      {
        "name": "dry_run",
        "type": "boolean",
        "required": false,
        "default": "false",
        "description": "When true, validate and preview without writing the proposal. Defaults to false.",
        "control": "toggle"
      }
    ],
    "returns": "A proposal-response object: {proposal_id, status (pending), kind (relation), dry_run, note} (MCP also includes an optional warnings array). Becomes a durable relation after kb.approve.",
    "view": "propose",
    "longRunning": false
  },
  {
    "name": "kb.approve",
    "group": "lifecycle",
    "mutates": true,
    "gated": false,
    "summary": "Approve a pending proposal, promoting it into a durable artifact (the review-gate decision). Use carefully.",
    "params": [
      {
        "name": "proposal_id",
        "type": "string",
        "required": true,
        "default": "",
        "description": "Id of the pending proposal to approve.",
        "control": "text",
        "refKind": "proposal"
      },
      {
        "name": "reason",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Optional reason recorded with the approval in the audit log.",
        "control": "textarea"
      }
    ],
    "returns": "Object {kind, id}: kind is the lowercased artifact class name (claim|page|entity|relation), id is the new durable artifact's id. Raises an error if the proposal is missing or not pending.",
    "view": "review",
    "longRunning": false
  },
  {
    "name": "kb.reject",
    "group": "lifecycle",
    "mutates": true,
    "gated": false,
    "summary": "Reject a pending proposal (the negative review-gate decision); it is not promoted to a durable artifact.",
    "params": [
      {
        "name": "proposal_id",
        "type": "string",
        "required": true,
        "default": "",
        "description": "Id of the pending proposal to reject.",
        "control": "text",
        "refKind": "proposal"
      },
      {
        "name": "reason",
        "type": "string",
        "required": true,
        "default": "",
        "description": "Required human-readable reason for the rejection; recorded in the audit log.",
        "control": "textarea"
      }
    ],
    "returns": "Object {proposal_id, status: 'rejected', reason} (the reason field is present over MCP; JSONL returns {proposal_id, status: 'rejected'}).",
    "view": "review",
    "longRunning": false
  },
  {
    "name": "kb.reject_extracted",
    "group": "lifecycle",
    "mutates": true,
    "gated": false,
    "summary": "Mass-reject pending edges filed by the auto-extractor (issue #224). Scope to one page's edges, or omit page_id to clear every pending auto-extracted edge across the KB.",
    "params": [
      {
        "name": "page_id",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Optional page id; when set, only that page's pending auto-extracted edges are rejected. Omit to reject all pending auto-extracted edges KB-wide.",
        "control": "text",
        "refKind": "page"
      },
      {
        "name": "reason",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Optional rejection reason recorded in the audit log; applied only when non-empty.",
        "control": "textarea"
      }
    ],
    "returns": "Object {rejected: [proposal_id, ...]} listing the ids of the proposals that were rejected.",
    "view": "review",
    "longRunning": false
  },
  {
    "name": "kb.expire",
    "group": "lifecycle",
    "mutates": true,
    "gated": false,
    "summary": "Expire stale pending proposals based on the configured age threshold. Dry-run by default â pass apply=true to actually expire them.",
    "params": [
      {
        "name": "apply",
        "type": "boolean",
        "required": false,
        "default": "false",
        "description": "When false (default) this is a dry run that only reports what would expire. Set true to actually expire the stale proposals.",
        "control": "toggle"
      },
      {
        "name": "days",
        "type": "integer",
        "required": false,
        "default": "",
        "description": "Optional override for the staleness threshold in days. When omitted, the KB's configured threshold is used (threshold_days; expiry is disabled when that is 0).",
        "control": "integer"
      }
    ],
    "returns": "Object {threshold_days, enabled (threshold_days > 0), dry_run (= not apply), would_expire: [ids], expired: [ids]}. On a dry run would_expire is populated and expired is empty; with apply=true expired holds the actually-expired ids.",
    "view": "review",
    "longRunning": false
  },
  {
    "name": "kb.supersede",
    "group": "lifecycle",
    "mutates": true,
    "gated": false,
    "summary": "Mark an existing claim as superseded by another existing claim. Direct mutation on durable claims (not a proposal): sets old.status=SUPERSEDED, old.superseded_by=new, adds new.supersedes link, mirrors a SUPERSEDES relation into the graph, and writes a claim.supersede audit event. Idempotent on retry. Both claims must already exist; a claim cannot supersede itself.",
    "params": [
      {
        "name": "old_claim_id",
        "type": "string",
        "required": true,
        "default": "",
        "description": "ID of the claim being superseded (must already exist).",
        "control": "text",
        "refKind": "claim"
      },
      {
        "name": "new_claim_id",
        "type": "string",
        "required": true,
        "default": "",
        "description": "ID of the newer claim that supersedes the old one (must already exist; cannot equal old_claim_id).",
        "control": "text",
        "refKind": "claim"
      }
    ],
    "returns": "Object {old: old claim id, new: new claim id, status: old claim status value (e.g. \"superseded\")}.",
    "view": "review",
    "longRunning": false
  },
  {
    "name": "kb.contradict",
    "group": "lifecycle",
    "mutates": true,
    "gated": false,
    "summary": "Record that two existing claims contradict each other (symmetric). Direct mutation: adds each claim id to the other's contradicts list, sets both statuses to CONTESTED, creates a CONTRADICTS relation in the graph, and writes a claim.contradict audit event. Both claims must already exist.",
    "params": [
      {
        "name": "claim_a",
        "type": "string",
        "required": true,
        "default": "",
        "description": "ID of the first claim (must already exist).",
        "control": "text",
        "refKind": "claim"
      },
      {
        "name": "claim_b",
        "type": "string",
        "required": true,
        "default": "",
        "description": "ID of the second claim (must already exist).",
        "control": "text",
        "refKind": "claim"
      }
    ],
    "returns": "Object {a: claim_a id, b: claim_b id, relation_id: id of the created CONTRADICTS relation}.",
    "view": "review",
    "longRunning": false
  },
  {
    "name": "kb.archive",
    "group": "lifecycle",
    "mutates": true,
    "gated": false,
    "summary": "Archive an existing claim. Direct mutation: sets the claim's status to ARCHIVED, bumps updated_at, and writes a claim.archive audit event.",
    "params": [
      {
        "name": "claim_id",
        "type": "string",
        "required": true,
        "default": "",
        "description": "ID of the claim to archive (must already exist).",
        "control": "text",
        "refKind": "claim"
      }
    ],
    "returns": "Object {id: claim id, status: new status value (\"archived\")}.",
    "view": "review",
    "longRunning": false
  },
  {
    "name": "kb.confirm",
    "group": "lifecycle",
    "mutates": true,
    "gated": false,
    "summary": "Re-confirm a stale claim. Direct mutation: bumps last_confirmed_at (and updated_at) to now; if the claim was in WORKING status it is promoted to ACTIONABLE. Writes a claim.confirm audit event.",
    "params": [
      {
        "name": "claim_id",
        "type": "string",
        "required": true,
        "default": "",
        "description": "ID of the claim to re-confirm (must already exist).",
        "control": "text",
        "refKind": "claim"
      }
    ],
    "returns": "Object {id: claim id, last_confirmed_at: ISO-8601 timestamp string (or null if unset)}.",
    "view": "review",
    "longRunning": false
  },
  {
    "name": "kb.cite",
    "group": "read",
    "mutates": false,
    "gated": false,
    "summary": "Return the resolved citations backing a claim. For each evidence ref on the claim, returns either a full Evidence record (when the ref is an Evidence id) or a minimal source dict (when the ref is a bare Source id), or a {kind:'missing', ref} marker if it resolves to neither. Read-only; writes no audit event.",
    "params": [
      {
        "name": "claim_id",
        "type": "string",
        "required": true,
        "default": "",
        "description": "ID of the claim whose citations to resolve (must already exist).",
        "control": "text",
        "refKind": "claim"
      }
    ],
    "returns": "Array of citation entries. Each is either an Evidence object (model_dump), or {kind:\"source\", source_id, title, locator, hash}, or {kind:\"missing\", ref}.",
    "view": "browse",
    "longRunning": false
  },
  {
    "name": "kb.source_verify",
    "group": "audit",
    "mutates": false,
    "gated": false,
    "summary": "Re-hash every registered source and report drift. Recomputes the stored hash of each source and checks external status, returning a per-source verification row. Takes no parameters. Verifies integrity rather than asserting new knowledge, so it is not review-gated.",
    "params": [],
    "returns": "Array of {source_id, title, stored_ok (bool), external_status, note} â one row per source.",
    "view": "maintenance",
    "longRunning": true
  },
  {
    "name": "kb.session_start",
    "group": "session",
    "mutates": true,
    "gated": false,
    "summary": "Start a new work session. Creates and persists a Session record (server-generated id, agent from VOUCH_AGENT/actor, start timestamp), writes a session.start audit event, and registers volunteer-context push for the session. Groups every proposal the agent files during the block.",
    "params": [
      {
        "name": "task",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Optional short description of the task this session is working on.",
        "control": "textarea"
      },
      {
        "name": "note",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Optional free-form note attached to the session at start.",
        "control": "textarea"
      }
    ],
    "returns": "The created Session object (model_dump): id, agent, task, note, started_at, ended_at (null), proposal_ids, etc.",
    "view": "sessions",
    "longRunning": false
  },
  {
    "name": "kb.session_end",
    "group": "session",
    "mutates": true,
    "gated": false,
    "summary": "End an active session. Sets ended_at, optionally appends a note, backfills proposal_ids by scanning proposals whose session_id matches, persists the session, and writes a session.end audit event. Idempotent: a session already ended is returned unchanged.",
    "params": [
      {
        "name": "session_id",
        "type": "string",
        "required": true,
        "default": "",
        "description": "ID of the session to end (must already exist).",
        "control": "text",
        "refKind": "session"
      },
      {
        "name": "note",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Optional closing note; appended to any existing session note.",
        "control": "textarea"
      }
    ],
    "returns": "The updated Session object (model_dump): id, agent, task, note, started_at, ended_at, proposal_ids.",
    "view": "sessions",
    "longRunning": false
  },
  {
    "name": "kb.volunteer_context",
    "group": "session",
    "mutates": true,
    "gated": false,
    "summary": "Poll the confidence-gated context volunteered for an active session and drain the pending offers. By default clears the queue after reading (clear=true). Mutates only the in-memory pending-offers buffer for the session.",
    "params": [
      {
        "name": "session_id",
        "type": "string",
        "required": true,
        "default": "",
        "description": "ID of the active session whose volunteered context to drain.",
        "control": "text",
        "refKind": "session"
      },
      {
        "name": "clear",
        "type": "boolean",
        "required": false,
        "default": "true",
        "description": "If true (default), remove the drained offers from the pending buffer; if false, leave them so they can be polled again.",
        "control": "toggle"
      }
    ],
    "returns": "Object {volunteers: array of offer dicts (each o.to_dict())} that were pending for the session.",
    "view": "sessions",
    "longRunning": false
  },
  {
    "name": "kb.crystallize",
    "group": "session",
    "mutates": true,
    "gated": false,
    "summary": "Approve every still-pending proposal filed under a session in one shot (host must trust the agent â this is the approval step, not a new proposal). Optionally writes a durable session-summary Page linking the approved claims. Records each approval and a session.crystallize audit event; per-proposal failures are collected, not fatal.",
    "params": [
      {
        "name": "session_id",
        "type": "string",
        "required": true,
        "default": "",
        "description": "ID of the session whose pending proposals to approve (must already exist).",
        "control": "text",
        "refKind": "session"
      },
      {
        "name": "write_summary_page",
        "type": "boolean",
        "required": false,
        "default": "true",
        "description": "If true (default), create a session-summary Page linking the crystallized claims when at least one proposal was approved.",
        "control": "toggle"
      }
    ],
    "returns": "Object {session_id, approved: [artifact ids], failures: [{proposal_id, error, error_type}], summary_page_id: page id or null}.",
    "view": "sessions",
    "longRunning": false
  },
  {
    "name": "kb.index_rebuild",
    "group": "maintenance",
    "mutates": true,
    "gated": false,
    "summary": "Drop and rebuild the derived SQLite index (state.db, FTS5 + optional embeddings) from the durable on-disk files. Touches only the derived index, never the authoritative yaml/md/jsonl. Takes no parameters.",
    "params": [],
    "returns": "A rebuild summary object from health.rebuild_index (counts of indexed artifacts).",
    "view": "maintenance",
    "longRunning": true
  },
  {
    "name": "kb.lint",
    "group": "maintenance",
    "mutates": false,
    "gated": false,
    "summary": "Run KB hygiene checks and return findings (e.g. stale claims, missing citations, dangling refs). Read-only health report; does not modify artifacts. Configurable staleness threshold via stale_days.",
    "params": [
      {
        "name": "stale_days",
        "type": "integer",
        "required": false,
        "default": "180",
        "description": "Age in days after which a claim is flagged as stale (default 180).",
        "control": "integer"
      }
    ],
    "returns": "Object {ok: bool, findings: [{severity, code, message, object_ids}], counts: {...}}.",
    "view": "maintenance",
    "longRunning": false
  },
  {
    "name": "kb.doctor",
    "group": "maintenance",
    "mutates": false,
    "gated": false,
    "summary": "Run deeper structural-integrity diagnostics over the KB (index consistency, durable-file vs derived-index drift, etc.) and return findings. Read-only health report; takes no parameters and does not modify artifacts.",
    "params": [],
    "returns": "Object {ok: bool, findings: [{severity, code, message, object_ids}], counts: {...}}.",
    "view": "maintenance",
    "longRunning": false
  },
  {
    "name": "kb.export",
    "group": "export-import",
    "mutates": true,
    "gated": false,
    "summary": "Write a portable .tar.gz bundle of every committed artifact (claims, pages, sources, entities, relations, evidence, sessions, decided proposals) plus a manifest.json to disk. Writes a file but does not touch the KB or the review gate.",
    "params": [
      {
        "name": "out_path",
        "type": "string",
        "required": true,
        "default": "",
        "description": "Filesystem path where the bundle .tar.gz will be written (the export destination).",
        "control": "file",
        "file": "save"
      }
    ],
    "returns": "Object with bundle_id (sha256 of the sorted artifact-hash list), files (integer count of artifacts in the bundle), and out (the path it was written to).",
    "view": "export-import",
    "longRunning": true
  },
  {
    "name": "kb.export_check",
    "group": "export-import",
    "mutates": false,
    "gated": false,
    "summary": "Validate an existing bundle file: re-hash its contents against the manifest and report any integrity issues. Read-only inspection of a bundle, no KB involved.",
    "params": [
      {
        "name": "bundle_path",
        "type": "string",
        "required": true,
        "default": "",
        "description": "Path to the bundle .tar.gz to validate.",
        "control": "file",
        "file": "open"
      }
    ],
    "returns": "Object with ok (boolean, true if the bundle is internally consistent), bundle_id (string), files_checked (integer count), and issues (list of strings describing any problems found).",
    "view": "export-import",
    "longRunning": false
  },
  {
    "name": "kb.import_check",
    "group": "export-import",
    "mutates": false,
    "gated": false,
    "summary": "Dry-run an import against the current KB: diff each artifact in the bundle into new / conflict / identical buckets so a caller can decide an on_conflict policy before applying. Read-only; nothing is written.",
    "params": [
      {
        "name": "bundle_path",
        "type": "string",
        "required": true,
        "default": "",
        "description": "Path to the bundle .tar.gz to diff against the current KB.",
        "control": "file",
        "file": "open"
      }
    ],
    "returns": "Object with ok (boolean), bundle_id (string), new_files (list of artifact ids/paths not present locally), conflicts (list of artifacts whose local content differs), identical_files (integer count of byte-identical artifacts), and issues (list of validation problems).",
    "view": "export-import",
    "longRunning": false
  },
  {
    "name": "kb.import_apply",
    "group": "export-import",
    "mutates": true,
    "gated": false,
    "summary": "Merge a validated bundle into the current KB with an explicit conflict policy, then rebuild the search index. Writes artifacts directly to disk (an import path, not a proposal) and is recorded in the audit log under the import actor.",
    "params": [
      {
        "name": "bundle_path",
        "type": "string",
        "required": true,
        "default": "",
        "description": "Path to the bundle .tar.gz to apply.",
        "control": "file",
        "file": "open"
      },
      {
        "name": "on_conflict",
        "type": "string",
        "required": false,
        "default": "skip",
        "description": "Conflict resolution policy when a bundle artifact differs from the local copy. One of: skip (keep local, default), overwrite (take bundle), fail (abort if any conflict exists).",
        "control": "select",
        "enum": [
          "skip",
          "overwrite",
          "fail"
        ]
      }
    ],
    "returns": "Object summarizing the merge, including on_conflict (the policy used) and counts of applied / skipped / conflicting artifacts. The index is rebuilt as a side effect.",
    "view": "export-import",
    "longRunning": true
  },
  {
    "name": "kb.audit",
    "group": "audit",
    "mutates": false,
    "gated": false,
    "summary": "Return the last N events from the append-only audit log, filtered to the caller's viewer scope (project/agent). Read-only view over the authoritative event stream.",
    "params": [
      {
        "name": "tail",
        "type": "integer",
        "required": false,
        "default": "50",
        "description": "How many of the most-recent audit events to return.",
        "control": "integer"
      },
      {
        "name": "project",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Optional project scope override for the viewer; restricts which events are visible. Defaults to the configured viewer's project.",
        "control": "text"
      },
      {
        "name": "agent",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Optional agent scope override for the viewer; restricts which events are visible. Defaults to the configured viewer's agent.",
        "control": "text"
      }
    ],
    "returns": "Object with viewer ({project, agent} actually applied) and events (list of audit-event objects, json-serialized, ordered oldest-to-newest within the tail window).",
    "view": "audit",
    "longRunning": false
  },
  {
    "name": "kb.reindex_embeddings",
    "group": "maintenance",
    "mutates": true,
    "gated": false,
    "summary": "Re-encode every artifact under the current embedding adapter, backfilling the embedding index. Rebuilds derived state (embeddings/index), not gated KB content.",
    "params": [
      {
        "name": "backfill",
        "type": "boolean",
        "required": false,
        "default": "false",
        "description": "Backfill embeddings for artifacts that are missing them. (MCP surface accepts this flag; the JSONL handler always backfills.)",
        "control": "toggle"
      },
      {
        "name": "force",
        "type": "boolean",
        "required": false,
        "default": "false",
        "description": "Re-encode all artifacts even if an up-to-date embedding already exists.",
        "control": "toggle"
      },
      {
        "name": "model",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Optional embedding model name to load/use for this run. Defaults to the configured adapter. (MCP surface only.)",
        "control": "text"
      }
    ],
    "returns": "Object with touched (integer count of artifacts re-encoded) and, on the MCP surface, model (the current embedding model name).",
    "view": "maintenance",
    "longRunning": true
  },
  {
    "name": "kb.dedup_scan",
    "group": "maintenance",
    "mutates": false,
    "gated": false,
    "summary": "Find near-duplicate artifacts by embedding cosine similarity above a threshold. Read-only scan over derived embeddings; reports candidate pairs without changing the KB.",
    "params": [
      {
        "name": "threshold",
        "type": "number",
        "required": false,
        "default": "0.95",
        "description": "Cosine-similarity cutoff (0-1); pairs at or above this are reported as near-duplicates.",
        "control": "slider"
      },
      {
        "name": "dry_run",
        "type": "boolean",
        "required": false,
        "default": "false",
        "description": "Run the scan without taking any follow-up action (scan is non-mutating either way; this flag is passed through to the dedup routine).",
        "control": "toggle"
      }
    ],
    "returns": "Object with duplicates (list of near-duplicate candidate rows/pairs) and, on the MCP surface, the threshold used.",
    "view": "maintenance",
    "longRunning": true
  },
  {
    "name": "kb.eval_embeddings",
    "group": "maintenance",
    "mutates": false,
    "gated": false,
    "summary": "Run a retrieval-quality evaluation over a JSONL queries file, scoring top-k recall against the embedding index. Read-only benchmarking of the embedding adapter.",
    "params": [
      {
        "name": "queries_path",
        "type": "string",
        "required": true,
        "default": "",
        "description": "Path to a JSONL file of evaluation queries (each line a query with expected results) to score retrieval against.",
        "control": "file",
        "file": "open"
      },
      {
        "name": "k",
        "type": "integer",
        "required": false,
        "default": "10",
        "description": "Number of top results to retrieve per query for the eval (the k in recall@k).",
        "control": "integer"
      }
    ],
    "returns": "Object of retrieval-eval metrics (e.g. per-query and aggregate recall@k / hit-rate scores) as produced by the scorer.",
    "view": "maintenance",
    "longRunning": true
  },
  {
    "name": "kb.embeddings_stats",
    "group": "maintenance",
    "mutates": false,
    "gated": false,
    "summary": "Report embedding-index health: active model identity, per-kind artifact counts, and query-cache statistics. Read-only inspection of derived embedding state.",
    "params": [],
    "returns": "Object with model (embedding model name), model_version (MCP surface only), dim (embedding dimensionality, MCP surface only), counts (map of artifact kind -> number embedded), and query_cache (cache-hit/size statistics).",
    "view": "maintenance",
    "longRunning": false
  },
  {
    "name": "kb.why",
    "group": "graph",
    "mutates": false,
    "gated": false,
    "summary": "Backward provenance for a claim: walks cites / derived-from / supersedes / contradicts / proposed-in / approved-by edges outward up to depth hops, each leaf carrying its audit timestamp and originating session. Read-only graph query.",
    "params": [
      {
        "name": "claim_id",
        "type": "string",
        "required": true,
        "default": "",
        "description": "Id of the claim (or artifact) whose backward provenance to expand.",
        "control": "text",
        "refKind": "claim"
      },
      {
        "name": "depth",
        "type": "integer",
        "required": false,
        "default": "3",
        "description": "How many hops of provenance to expand outward. Must be >= 0.",
        "control": "integer"
      }
    ],
    "returns": "Object with schema_version, root (the claim_id), node_kind (kind of the root node), depth, and provenance (a nested tree of provenance entries, each with kind, target, source/target kind, event_ts, session_id, cycle flag, and children).",
    "view": "graph",
    "longRunning": false
  },
  {
    "name": "kb.trace",
    "group": "graph",
    "mutates": false,
    "gated": false,
    "summary": "Find the shortest typed-edge path between two artifacts (edges crossable in either direction). Read-only graph query; returns found=false with an empty path when the two are disconnected.",
    "params": [
      {
        "name": "from",
        "type": "string",
        "required": true,
        "default": "",
        "description": "Id of the starting artifact. NOTE: the MCP tool uses the key 'from_id'; over JSONL the param key is 'from'.",
        "control": "text",
        "refKind": "node"
      },
      {
        "name": "to",
        "type": "string",
        "required": true,
        "default": "",
        "description": "Id of the target artifact. NOTE: the MCP tool uses the key 'to_id'; over JSONL the param key is 'to'.",
        "control": "text",
        "refKind": "node"
      }
    ],
    "returns": "Object with schema_version, from, to, found (boolean), length (number of edges), nodes (ordered list of node ids on the path), and path (list of step objects each with from, to, kind, reversed).",
    "view": "graph",
    "longRunning": false
  },
  {
    "name": "kb.impact",
    "group": "graph",
    "mutates": false,
    "gated": false,
    "summary": "Forward impact for a claim: what depends on it up to depth hops, plus optional dry-run breakage if a destructive op is named. Read-only; the op dry-run reports breakage against the in-memory graph without writing anything.",
    "params": [
      {
        "name": "claim_id",
        "type": "string",
        "required": true,
        "default": "",
        "description": "Id of the claim (or artifact) whose forward dependents to expand.",
        "control": "text",
        "refKind": "claim"
      },
      {
        "name": "depth",
        "type": "integer",
        "required": false,
        "default": "1",
        "description": "How many hops of dependents to expand. Must be >= 0.",
        "control": "integer"
      },
      {
        "name": "op",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Optional lifecycle operation to dry-run for breakage analysis. One of: archive, contradict, supersede. When set, reports which active pages would carry a stale reference.",
        "control": "select",
        "enum": [
          "archive",
          "contradict",
          "supersede"
        ]
      }
    ],
    "returns": "Object with schema_version, root, node_kind, depth, op (echoed or null), dependents (nested tree of dependent entries with kind/source/source_kind/event_ts/session_id/cycle/dependents), breakage (list of active pages that would break under op, each with id/kind/status/via/title), and blocking (boolean, true iff breakage is non-empty).",
    "view": "graph",
    "longRunning": false
  },
  {
    "name": "kb.graph_export",
    "group": "graph",
    "mutates": false,
    "gated": false,
    "summary": "Render the full provenance DAG, or a single session's subgraph, as Graphviz dot or mermaid flowchart text. Read-only export.",
    "params": [
      {
        "name": "session",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Optional session id; when set, only that session's proposed claims and their edges are rendered (the subgraph). Omit for the whole DAG.",
        "control": "text"
      },
      {
        "name": "format",
        "type": "string",
        "required": false,
        "default": "dot",
        "description": "Output format for the rendered graph. One of: dot (Graphviz), mermaid (mermaid flowchart).",
        "control": "select",
        "enum": [
          "dot",
          "mermaid"
        ]
      }
    ],
    "returns": "Object with format (the format used) and graph (the rendered graph as a text string in the chosen syntax).",
    "view": "graph",
    "longRunning": false
  },
  {
    "name": "kb.provenance_rebuild",
    "group": "maintenance",
    "mutates": true,
    "gated": false,
    "summary": "Rebuild the prov_edges cache from the durable artifact files and return the resulting edge count. Regenerates derived provenance state; does not change committed KB content.",
    "params": [],
    "returns": "Object with edges (integer count of provenance edges in the rebuilt cache).",
    "view": "maintenance",
    "longRunning": true
  }
]

export type MethodName = "kb.capabilities" | "kb.status" | "kb.stats" | "kb.search" | "kb.neighbors" | "kb.context" | "kb.synthesize" | "kb.read_page" | "kb.read_claim" | "kb.read_entity" | "kb.read_relation" | "kb.list_pages" | "kb.list_claims" | "kb.list_entities" | "kb.list_relations" | "kb.list_sources" | "kb.list_pending" | "kb.register_source" | "kb.register_source_from_path" | "kb.propose_claim" | "kb.propose_page" | "kb.propose_entity" | "kb.propose_relation" | "kb.approve" | "kb.reject" | "kb.reject_extracted" | "kb.expire" | "kb.supersede" | "kb.contradict" | "kb.archive" | "kb.confirm" | "kb.cite" | "kb.source_verify" | "kb.session_start" | "kb.session_end" | "kb.volunteer_context" | "kb.crystallize" | "kb.index_rebuild" | "kb.lint" | "kb.doctor" | "kb.export" | "kb.export_check" | "kb.import_check" | "kb.import_apply" | "kb.audit" | "kb.reindex_embeddings" | "kb.dedup_scan" | "kb.eval_embeddings" | "kb.embeddings_stats" | "kb.why" | "kb.trace" | "kb.impact" | "kb.graph_export" | "kb.provenance_rebuild"

export default methods
